# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import control_pb2 as control__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/ascend_maze.control.v1.NodeControl/Connect',
                request_serializer=control__pb2.AgentStreamMessage.SerializeToString,
                response_deserializer=control__pb2.ControllerStreamMessage.FromString,
                _registered_method=True)


class NodeControlServicer:
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=control__pb2.AgentStreamMessage.FromString,
                    response_serializer=control__pb2.ControllerStreamMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ascend_maze.control.v1.NodeControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ascend_maze.control.v1.NodeControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ascend_maze.control.v1.NodeControl/Connect',
            control__pb2.AgentStreamMessage.SerializeToString,
            control__pb2.ControllerStreamMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerEventSinkStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Report = channel.unary_unary(
                '/ascend_maze.control.v1.WorkerEventSink/Report',
                request_serializer=control__pb2.WorkerEventRequest.SerializeToString,
                response_deserializer=control__pb2.WorkerEventAck.FromString,
                _registered_method=True)


class WorkerEventSinkServicer:
    """Missing associated documentation comment in .proto file."""

    def Report(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerEventSinkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Report': grpc.unary_unary_rpc_method_handler(
                    servicer.Report,
                    request_deserializer=control__pb2.WorkerEventRequest.FromString,
                    response_serializer=control__pb2.WorkerEventAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ascend_maze.control.v1.WorkerEventSink', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ascend_maze.control.v1.WorkerEventSink', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerEventSink:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Report(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.WorkerEventSink/Report',
            control__pb2.WorkerEventRequest.SerializeToString,
            control__pb2.WorkerEventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LocalControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetControllerStatus = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/GetControllerStatus',
                request_serializer=control__pb2.GetControllerStatusRequest.SerializeToString,
                response_deserializer=control__pb2.GetControllerStatusResponse.FromString,
                _registered_method=True)


class LocalControlServicer:
    """Missing associated documentation comment in .proto file."""

    def GetControllerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocalControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetControllerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControllerStatus,
                    request_deserializer=control__pb2.GetControllerStatusRequest.FromString,
                    response_serializer=control__pb2.GetControllerStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ascend_maze.control.v1.LocalControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ascend_maze.control.v1.LocalControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LocalControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetControllerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/GetControllerStatus',
            control__pb2.GetControllerStatusRequest.SerializeToString,
            control__pb2.GetControllerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
